# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assist_expression.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 403)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dispalylabel = QtWidgets.QLabel(self.centralwidget)
        self.dispalylabel.setGeometry(QtCore.QRect(520, 150, 260, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispalylabel.sizePolicy().hasHeightForWidth())
        self.dispalylabel.setSizePolicy(sizePolicy)
        self.dispalylabel.setObjectName("dispalylabel")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 501, 351))
        font = QtGui.QFont()
        font.setFamily("文泉驿等宽微米黑")
        font.setPointSize(18)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_12.setGeometry(QtCore.QRect(20, 120, 71, 30))
        self.radioButton_12.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_19 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_19.setGeometry(QtCore.QRect(110, 120, 71, 30))
        self.radioButton_19.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_12.raise_()
        self.radioButton_19.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 120, 71, 30))
        self.radioButton_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(110, 120, 71, 30))
        self.radioButton_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(200, 120, 92, 30))
        self.radioButton_5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_6.setGeometry(QtCore.QRect(290, 120, 92, 30))
        self.radioButton_6.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_7.setGeometry(QtCore.QRect(380, 120, 71, 30))
        self.radioButton_7.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_7.setObjectName("radioButton_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 120, 92, 30))
        self.radioButton_8.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_9.setGeometry(QtCore.QRect(110, 120, 92, 30))
        self.radioButton_9.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_10.setGeometry(QtCore.QRect(200, 120, 71, 30))
        self.radioButton_10.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_10.setObjectName("radioButton_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 120, 92, 30))
        self.radioButton_11.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_13 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_13.setGeometry(QtCore.QRect(110, 120, 92, 30))
        self.radioButton_13.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_13.setObjectName("radioButton_13")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.radioButton_14 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_14.setGeometry(QtCore.QRect(20, 120, 71, 30))
        self.radioButton_14.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_15.setGeometry(QtCore.QRect(110, 120, 71, 30))
        self.radioButton_15.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_15.setObjectName("radioButton_15")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.radioButton_16 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_16.setGeometry(QtCore.QRect(20, 120, 113, 30))
        self.radioButton_16.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_17.setGeometry(QtCore.QRect(110, 120, 113, 30))
        self.radioButton_17.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_18.setGeometry(QtCore.QRect(200, 120, 113, 30))
        self.radioButton_18.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_18.setObjectName("radioButton_18")
        self.tabWidget.addTab(self.tab_5, "")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 40, 20, 331))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(520, 40, 260, 95))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(520, 140, 261, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.raise_()
        self.dispalylabel.raise_()
        self.line.raise_()
        self.textBrowser.raise_()
        self.line_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "expresionWin"))
        self.dispalylabel.setText(_translate("MainWindow", "视频窗口"))
        self.radioButton_12.setText(_translate("MainWindow", "吃饭"))
        self.radioButton_19.setText(_translate("MainWindow", "喝水"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "饮食"))
        self.radioButton_3.setText(_translate("MainWindow", "坐起"))
        self.radioButton_4.setText(_translate("MainWindow", "卧躺"))
        self.radioButton_5.setText(_translate("MainWindow", "左侧身"))
        self.radioButton_6.setText(_translate("MainWindow", "右侧身"))
        self.radioButton_7.setText(_translate("MainWindow", "曲腿"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "活动"))
        self.radioButton_8.setText(_translate("MainWindow", "肩颈部"))
        self.radioButton_9.setText(_translate("MainWindow", "躯干部"))
        self.radioButton_10.setText(_translate("MainWindow", "全身"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "按摩"))
        self.radioButton_11.setText(_translate("MainWindow", "听音乐"))
        self.radioButton_13.setText(_translate("MainWindow", "看视频"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "娱乐"))
        self.radioButton_14.setText(_translate("MainWindow", "升温"))
        self.radioButton_15.setText(_translate("MainWindow", "降温"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "调温"))
        self.radioButton_16.setText(_translate("MainWindow", "护士"))
        self.radioButton_17.setText(_translate("MainWindow", "医生"))
        self.radioButton_18.setText(_translate("MainWindow", "家人"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "人工帮助"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示信息：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">通过头部转动控制光标移动</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">头部左转5秒紧急呼救</p></body></html>"))
